import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f8f8',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingTop: 45,
    paddingBottom: 15,
    backgroundColor: '#FFFFFF',
  },
  backButton: {
    marginRight: 15,
    padding: 5,
  },
  backButtonImage: {
    width: 46,
    height: 46,
  },
  headerTextContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#3c3c3c',
    letterSpacing: 0.5,
  },
  headerSubtitle: {
    fontSize: 11,
    color: '#8c8c8c',
    marginTop: 2,
  },
  progressBarContainer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingBottom: 15,
  },
  progressBar: {
    height: 6,
    backgroundColor: '#e0e0e0',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#68bdee',
    borderRadius: 3,
  },
  fullWidthSeparator: {
    height: 1,
    backgroundColor: '#d0d0d0',
    width: '100%',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingTop: 15,
    paddingHorizontal: 20,
  },
  reviewHeader: {
    backgroundColor: '#e3f5ff',
    borderRadius: 12,
    padding: 30,
    alignItems: 'center',
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#d0d0d0',
  },
  checkIconContainer: {
    marginBottom: 15,
  },
  reviewIcon: {
    width: 58,
    height: 58,
  },
  reviewTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#3c3c3c',
    marginBottom: 8,
  },
  reviewSubtitle: {
    fontSize: 12,
    color: '#5c5c5c',
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    padding: 20,
    marginBottom: 15,
  },
  serviceCard: {
    backgroundColor: '#e3f5ff',
    borderWidth: 2,
    borderColor: '#68bdee',
  },
  paymentCard: {
    backgroundColor: '#e3f5ff',
  },
  paymentCardWithBlueBorder: {
    borderWidth: 2,
    borderColor: '#68bdee',
  },
  locationCard: {
    borderWidth: 1,
    borderColor: '#d0d0d0',
  },
  scheduleCard: {
    borderWidth: 1,
    borderColor: '#d0d0d0',
  },
  contactCard: {
    borderWidth: 1,
    borderColor: '#d0d0d0',
  },
  notesCard: {
    borderWidth: 1,
    borderColor: '#d0d0d0',
  },
  cancellationCard: {
    padding: 0,
    marginBottom: 15,
    backgroundColor: 'transparent',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  cardHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  cardHeaderIcon: {
    width: 20,
    height: 20,
  },
  cardTitle: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#3c3c3c',
    letterSpacing: 0.5,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  penIcon: {
    width: 16,
    height: 16,
  },
  editText: {
    fontSize: 12,
    fontWeight: '600',
  },
  underlineText: {
    textDecorationLine: 'underline',
  },
  serviceInfo: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  serviceIconNoContainer: {
    width: 40,
    height: 40,
    marginRight: 15,
  },
  serviceTextContainer: {
    flex: 1,
  },
  serviceName: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#3c3c3c',
    marginBottom: 4,
  },
  serviceTags: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  simpleTag: {
    fontSize: 10,
    color: '#3c3c3c',
    fontWeight: '400',
    textTransform: 'uppercase',
  },
  plusSign: {
    fontSize: 10,
    color: '#3c3c3c',
    fontWeight: '400',
  },
  serviceSpecificRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 4,
  },
  serviceSpecificText: {
    fontSize: 11,
    color: '#4CAF50',
    fontWeight: '500',
  },
  divider: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginVertical: 15,
  },
  vehicleDetailsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  detailColumn: {
    flexDirection: 'column',
    gap: 4,
  },
  licensePlateContainer: {
    flexDirection: 'column',
    gap: 4,
    alignItems: 'flex-end',
  },
  detailLabel: {
    fontSize: 11,
    color: '#5c5c5c',
    fontWeight: '500',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  detailValue: {
    fontSize: 14,
    color: '#3c3c3c',
    fontWeight: 'bold',
  },
  detailSubValue: {
    fontSize: 12,
    color: '#5c5c5c',
    marginTop: 2,
  },
  locationItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
  },
  locationIconBlue: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#68bdee',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  locationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FFFFFF',
  },
  locationIconOutline: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#68bdee',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  locationDotOutline: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#68bdee',
  },
  locationTextContainer: {
    flex: 1,
  },
  locationLabel: {
    fontSize: 11,
    color: '#8c8c8c',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  locationAddress: {
    fontSize: 13,
    color: '#3c3c3c',
    fontWeight: 'bold',
  },
  locationSkippedBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#e3f5ff',
    padding: 15,
    borderRadius: 8,
    gap: 10,
  },
  locationSkippedText: {
    fontSize: 12,
    color: '#3c3c3c',
    flex: 1,
  },
  distanceButtonFull: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    borderRadius: 8,
    width: '100%',
  },
  distanceText: {
    fontSize: 12,
    color: '#5c5c5c',
    fontWeight: '600',
  },
  scheduleInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  scheduleIconContainer: {
    width: 60,
    height: 60,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  scheduleImage: {
    width: 50,
    height: 50,
  },
  scheduleTextContainer: {
    flex: 1,
  },
  scheduleTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#3c3c3c',
    marginBottom: 4,
  },
  scheduleSubtitle: {
    fontSize: 11,
    color: '#5c5c5c',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  contactItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 20,
    gap: 12,
  },
  contactTextContainer: {
    flex: 1,
  },
  contactLabel: {
    fontSize: 11,
    color: '#8c8c8c',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  contactValue: {
    fontSize: 13,
    color: '#3c3c3c',
    fontWeight: 'bold',
  },
  headerDivider: {
    height: 1,
    backgroundColor: '#d0d0d0',
    marginBottom: 15,
    marginTop: -5,
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  paymentLabel: {
    fontSize: 13,
    color: '#5c5c5c',
    fontWeight: '500',
  },
  paymentValue: {
    fontSize: 13,
    color: '#3c3c3c',
    fontWeight: 'bold',
  },
  paymentRowTotal: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 15,
  },
  paymentLabelTotal: {
    fontSize: 14,
    color: '#3c3c3c',
    fontWeight: 'bold',
  },
  paymentValueTotal: {
    fontSize: 16,
    color: '#68bdee',
    fontWeight: 'bold',
  },
  bolderDivider: {
    height: 2,
    backgroundColor: '#a0a0a0',
    marginVertical: 15,
  },
  paymentMethod: {
    backgroundColor: 'transparent',
    paddingVertical: 8,
    paddingHorizontal: 0,
    alignSelf: 'flex-start',
  },
  paymentMethodLabel: {
    fontSize: 13,
    color: '#3c3c3c',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  notesText: {
    fontSize: 12,
    color: '#3c3c3c',
    marginTop: 10,
    lineHeight: 18,
  },
  notesPlaceholder: {
    fontSize: 12,
    color: '#b0b0b0',
    marginTop: 10,
    fontStyle: 'italic',
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#e3f5ff',
    padding: 15,
    borderRadius: 12,
    marginBottom: 15,
    gap: 12,
    borderWidth: 1,
    borderColor: '#d0d0d0',
  },
  checkbox: {
    width: 18,
    height: 18,
    borderWidth: 2,
    borderColor: '#68bdee',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFF',
  },
  checkboxDot: {
    width: 11,
    height: 11,
    borderRadius: 6,
    backgroundColor: '#68bdee',
  },
  checkboxText: {
    flex: 1,
    fontSize: 11,
    color: '#3c3c3c',
    lineHeight: 18,
  },
  linkText: {
    color: '#68bdee',
    fontWeight: '600',
  },
  safetyNotice: {
    flexDirection: 'row',
    backgroundColor: '#e3f5ff',
    padding: 20,
    borderRadius: 12,
    marginBottom: 15,
    gap: 15,
    borderWidth: 2,
    borderColor: '#68bdee',
  },
  safetyIconContainer: {
    marginTop: 2,
  },
  safetyTextContainer: {
    flex: 1,
  },
  safetyTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#3c3c3c',
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  safetyText: {
    fontSize: 11,
    color: '#5c5c5c',
    lineHeight: 18,
  },
  policyDividerFull: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginTop: 15,
    marginBottom: 15,
  },
  policyItem: {
    flexDirection: 'row',
    marginBottom: 12,
    paddingLeft: 5,
  },
  bulletPoint: {
    width: 4,
    height: 4,
    borderRadius: 2,
    marginTop: 7,
    marginRight: 12,
  },
  blackBullet: {
    backgroundColor: '#3c3c3c',
  },
  policyText: {
    fontSize: 11,
    color: '#5c5c5c',
    lineHeight: 18,
    flex: 1,
  },
  warningBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF3E0',
    padding: 15,
    borderRadius: 12,
    gap: 12,
    marginBottom: 15,
    borderWidth: 2,
    borderColor: '#F57C00',
  },
  warningText: {
    fontSize: 12,
    color: '#F57C00',
    fontWeight: '600',
    flex: 1,
  },
  bottomContainer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 15,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  confirmButton: {
    backgroundColor: '#68bdee',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  confirmButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  backEditButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#e0e0e0',
    marginBottom: 10,
  },
  backEditButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#3c3c3c',
  },
  disclaimerText: {
    fontSize: 10,
    color: '#8c8c8c',
    textAlign: 'center',
    lineHeight: 14,
  },
});
