import { Ionicons } from '@expo/vector-icons';
import AsyncStorage from '@react-native-async-storage/async-storage';
import * as Location from 'expo-location';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useEffect, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  Dimensions,
  Image,
  KeyboardAvoidingView,
  Modal,
  Platform,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  TouchableOpacity,
  View,
} from 'react-native';
import MapView, { Marker, Polyline, Region } from 'react-native-maps';

const { width, height } = Dimensions.get('window');



export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f8f8',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
    paddingTop: Platform.OS === 'ios' ? height * 0.06 : height * 0.03,
    paddingBottom: height * 0.02,
    backgroundColor: '#FFFFFF',
  },
  backButton: {
    marginRight: width * 0.04,
  },
  backButtonImage: {
    width: width * 0.12,
    height: width * 0.12,
    maxWidth: 46,
    maxHeight: 46,
  },
  headerTextContainer: {
    flex: 1,
  },
  headerTitle: {
    fontSize: Math.min(16, width * 0.04),
    fontWeight: 'bold',
    color: '#3c3c3c',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  headerSubtitle: {
    fontSize: Math.min(11, width * 0.03),
    color: '#8c8c8c',
    marginTop: 2,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  progressBarContainer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: width * 0.05,
    paddingBottom: height * 0.02,
  },
  progressBar: {
    height: 6,
    backgroundColor: '#e0e0e0',
    borderRadius: 3,
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#68bdee',
    borderRadius: 3,
  },
  // New styles for service type indicator
  serviceTypeIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.015,
    backgroundColor: '#FFFFFF',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  destinationService: {
    backgroundColor: '#f5f5f5',
  },
  locationOnlyService: {
    backgroundColor: '#e3f5ff',
  },
  serviceTypeText: {
    fontSize: Math.min(12, width * 0.03),
    marginLeft: 8,
    flex: 1,
  },
  destinationServiceText: {
    color: '#3c3c3c',
  },
  locationOnlyServiceText: {
    color: '#68bdee',
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: height * 0.02,
  },
  mapContainer: {
    height: height * 0.35,
    maxHeight: 400,
    position: 'relative',
    backgroundColor: '#e0e0e0',
  },
  map: {
    width: '100%',
    height: '100%',
  },
  mapLoader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10,
  },
  mapLoaderText: {
    marginTop: 10,
    fontSize: Math.min(14, width * 0.035),
    color: '#3c3c3c',
  },
  mapLabel: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: [{ translateX: -40 }, { translateY: -12 }],
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    paddingHorizontal: width * 0.04,
    paddingVertical: height * 0.01,
    borderRadius: 20,
  },
  mapLabelText: {
    fontSize: Math.min(12, width * 0.03),
    fontWeight: 'bold',
    color: '#3c3c3c',
    letterSpacing: 0.5,
  },
  locationButton: {
    position: 'absolute',
    bottom: height * 0.02,
    right: width * 0.05,
    width: width * 0.12,
    height: width * 0.12,
    maxWidth: 50,
    maxHeight: 50,
    borderRadius: (width * 0.12) / 2,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  currentLocationIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#E8F5E9',
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.015,
    marginTop: 1,
  },
  currentLocationText: {
    fontSize: Math.min(12, width * 0.03),
    color: '#2E7D32',
    marginLeft: 8,
    flex: 1,
  },
  formSection: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: width * 0.05,
    paddingTop: height * 0.03,
    paddingBottom: height * 0.02,
  },
  inputSection: {
    marginBottom: height * 0.03,
    position: 'relative',
    zIndex: 1,
  },
  waypointSection: {
    marginBottom: height * 0.02,
  },
  dropoffSection: {
    marginTop: height * 0.01,
  },
  inputSectionFocused: {
    zIndex: 1000,
  },
  inputLabel: {
    fontSize: Math.min(12, width * 0.03),
    fontWeight: '600',
    color: '#3c3c3c',
    marginBottom: height * 0.015,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  required: {
    color: '#ff4444',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#e0e0e0',
    borderRadius: 12,
    paddingHorizontal: width * 0.04,
    paddingVertical: Platform.OS === 'ios' ? height * 0.015 : 0,
    minHeight: 50,
    backgroundColor: '#FFFFFF',
  },
  locationDot: {
    width: width * 0.03,
    height: width * 0.03,
    maxWidth: 12,
    maxHeight: 12,
    borderRadius: (width * 0.03) / 2,
    backgroundColor: '#68bdee',
    marginRight: width * 0.03,
  },
  locationDotEmpty: {
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: '#b0b0b0',
  },
  locationDotActive: {
    borderWidth: 2,
    borderColor: '#68bdee',
  },
  input: {
    flex: 1,
    fontSize: Math.min(14, width * 0.035),
    color: '#3c3c3c',
    paddingVertical: Platform.OS === 'ios' ? height * 0.015 : 0,
  },
  inputIcon: {
    marginLeft: width * 0.02,
  },
  suggestionsContainer: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    marginTop: 4,
    maxHeight: height * 0.3,
    zIndex: 2000,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  loader: {
    padding: height * 0.02,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: height * 0.015,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  suggestionTextContainer: {
    flex: 1,
    marginLeft: width * 0.03,
  },
  suggestionTitle: {
    fontSize: Math.min(14, width * 0.035),
    fontWeight: '600',
    color: '#3c3c3c',
    marginBottom: 2,
  },
  suggestionAddress: {
    fontSize: Math.min(12, width * 0.03),
    color: '#8c8c8c',
  },
  waypointHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: height * 0.01,
  },
  waypointControls: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  waypointControlButton: {
    padding: width * 0.02,
    marginLeft: width * 0.01,
  },
  addStopButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#68bdee',
    borderRadius: 12,
    paddingVertical: height * 0.018,
    marginBottom: height * 0.035,
  },
  addStopText: {
    fontSize: Math.min(14, width * 0.035),
    fontWeight: '600',
    color: '#68bdee',
    marginLeft: width * 0.02,
  },
  savedLocationsSection: {
    marginTop: height * 0.01,
  },
  savedLocationsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: height * 0.018,
  },
  savedLocationsTitle: {
    fontSize: Math.min(12, width * 0.03),
    fontWeight: '600',
    color: '#3c3c3c',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  viewAllText: {
    fontSize: Math.min(12, width * 0.03),
    color: '#68bdee',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  savedLocationCard: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 12,
    padding: width * 0.04,
    marginBottom: height * 0.015,
    backgroundColor: '#FFFFFF',
  },
  savedLocationIconContainer: {
    marginRight: width * 0.04,
  },
  savedLocationIconCircle: {
    width: width * 0.12,
    height: width * 0.12,
    maxWidth: 50,
    maxHeight: 50,
    borderRadius: (width * 0.12) / 2,
    backgroundColor: '#e3f5ff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  savedLocationEmoji: {
    fontSize: Math.min(24, width * 0.06),
  },
  savedLocationInfo: {
    flex: 1,
  },
  savedLocationTitle: {
    fontSize: Math.min(14, width * 0.035),
    fontWeight: 'bold',
    color: '#3c3c3c',
    marginBottom: 4,
  },
  savedLocationAddress: {
    fontSize: Math.min(12, width * 0.03),
    color: '#8c8c8c',
  },
  addLocationButton: {
    marginLeft: width * 0.02,
  },
  emptySavedContainer: {
    padding: height * 0.03,
    alignItems: 'center',
    backgroundColor: '#f8f8f8',
    borderRadius: 12,
  },
  emptySavedText: {
    fontSize: Math.min(14, width * 0.035),
    color: '#8c8c8c',
  },
  showMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: height * 0.015,
    marginTop: height * 0.01,
    borderWidth: 1,
    borderColor: '#68bdee',
    borderRadius: 8,
    backgroundColor: '#f0f9ff',
  },
  showMoreButtonText: {
    fontSize: Math.min(14, width * 0.035),
    color: '#68bdee',
    fontWeight: '600',
    marginRight: width * 0.02,
  },
  bottomContainer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: width * 0.05,
    paddingVertical: height * 0.02,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  continueButton: {
    backgroundColor: '#68bdee',
    paddingVertical: height * 0.02,
    borderRadius: 12,
    alignItems: 'center',
  },
  continueButtonDisabled: {
    backgroundColor: '#b0b0b0',
    opacity: 0.5,
  },
  continueButtonText: {
    fontSize: Math.min(16, width * 0.04),
    fontWeight: 'bold',
    color: '#FFFFFF',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: width * 0.05,
    maxHeight: height * 0.9,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: height * 0.02,
  },
  modalTitle: {
    fontSize: Math.min(18, width * 0.045),
    fontWeight: 'bold',
    color: '#3c3c3c',
  },
  modalBody: {
    flex: 1,
  },
  modalLabel: {
    fontSize: Math.min(14, width * 0.035),
    fontWeight: '600',
    color: '#3c3c3c',
    marginBottom: height * 0.01,
    marginTop: height * 0.02,
  },
  modalInput: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    padding: width * 0.03,
    fontSize: Math.min(14, width * 0.035),
    color: '#3c3c3c',
  },
  locationTypeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: height * 0.02,
  },
  locationTypeButton: {
    flex: 1,
    alignItems: 'center',
    padding: width * 0.03,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    marginHorizontal: width * 0.01,
  },
  locationTypeButtonActive: {
    borderColor: '#68bdee',
    backgroundColor: '#e3f5ff',
  },
  locationTypeEmoji: {
    fontSize: Math.min(24, width * 0.06),
    marginBottom: 4,
  },
  locationTypeText: {
    fontSize: Math.min(12, width * 0.03),
    color: '#8c8c8c',
  },
  locationTypeTextActive: {
    color: '#68bdee',
    fontWeight: '600',
  },
  modalAddressPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    padding: width * 0.03,
    borderRadius: 8,
    marginTop: height * 0.02,
  },
  modalAddressText: {
    flex: 1,
    fontSize: Math.min(12, width * 0.03),
    color: '#3c3c3c',
    marginLeft: width * 0.02,
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: height * 0.03,
    paddingTop: height * 0.02,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
  },
  modalCancelButton: {
    flex: 1,
    padding: height * 0.018,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
    alignItems: 'center',
    marginRight: width * 0.02,
  },
  modalCancelButtonText: {
    fontSize: Math.min(14, width * 0.035),
    color: '#8c8c8c',
    fontWeight: '600',
  },
  modalSaveButton: {
    flex: 1,
    padding: height * 0.018,
    borderRadius: 8,
    backgroundColor: '#68bdee',
    alignItems: 'center',
    marginLeft: width * 0.02,
  },
  modalSaveButtonDisabled: {
    backgroundColor: '#b0b0b0',
  },
  modalSaveButtonText: {
    fontSize: Math.min(14, width * 0.035),
    color: '#FFFFFF',
    fontWeight: '600',
  },
});
