import { StyleSheet } from 'react-native';




export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  container: {
    flex: 1,
    paddingHorizontal: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  backButton: {
    position: 'absolute',
    top: 20,
    left: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#f8f8f8',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    zIndex: 10,
  },
  iconCircle: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#FEF9EC",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 24,
    borderWidth: 2,
    borderColor: "#f0b100",
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: "#3c3c3c",
    letterSpacing: 0.5,
    marginBottom: 12,
    textAlign: "center",
    textTransform: "uppercase",
  },
  description: {
    fontSize: 15,
    color: "#8c8c8c",
    fontWeight: "500",
    lineHeight: 22,
    textAlign: "center",
    letterSpacing: 0.2,
    marginBottom: 32,
  },
  btnGroup: {
    width: "100%",
    gap: 12,
    marginBottom: 24,
  },
  scheduleBtn: {
    borderRadius: 12,
    overflow: 'hidden',
    shadowColor: '#68bdee',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  gradientButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 16,
  },
  scheduleBtnText: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  viewAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    paddingVertical: 16,
    borderWidth: 2,
    borderColor: "#68bdee",
    backgroundColor: "#FFFFFF",
  },
  viewAllBtnText: {
    color: "#68bdee",
    fontSize: 15,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  homeBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 12,
    paddingVertical: 16,
    borderWidth: 2,
    borderColor: "#e0e0e0",
    backgroundColor: "#FFFFFF",
  },
  homeBtnText: {
    color: "#8c8c8c",
    fontSize: 15,
    fontWeight: "600",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  btnIcon: {
    marginRight: 8,
  },
  demandCard: {
    width: "100%",
    backgroundColor: "#FEF9EC",
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#f0b100",
    padding: 16,
  },
  demandHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 8,
  },
  demandTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#f0b100",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  demandText: {
    fontSize: 13,
    color: "#f0b100",
    fontWeight: "500",
    lineHeight: 20,
    letterSpacing: 0.2,
  },
});